apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels: 
    app: customer
spec:
  selector:
    matchLabels:
      app: customer
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: clintoncao/ms_customer
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: customer-svc
spec:
  selector:
    app:  customer
  ports:
  - port: 8080
    targetPort: 8080
