apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels: 
    app: order
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: clintoncao/ms_order
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: order-svc
spec:
  selector:
    app:  order
  ports:
  - port: 8080
    targetPort: 8080
